name: demo
description: A new Flutter demo project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_app_name: ^0.1.1
  flutter_html: ^2.2.1
  path_provider: ^2.0.9
  flutter_html_to_pdf: ^0.7.0
  qr_flutter: ^3.2.0
  qr_code_scanner: ^0.7.0
  permission_handler: ^9.2.0
  archive: ^3.3.0
  flutter_archive: ^4.2.0
  image_picker: ^0.8.5
  get: ^4.3.8
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  syncfusion_flutter_pdfviewer: ^20.1.50-beta

flutter_app_name:
  name: "Protean RC"

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/